#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import division

def temperature(arg , deger):
        # örnek kullanım temprature( 'fah' , 20 )
        # sıralama çok önemli » celcius , fahrenheit , kelvin , rankin
        anlam = { 'cel':'celcius' , 'fah':'fahrenheit' , 'kel':'kelvin' , 'rea':'rankin' }
        if ( arg in anlam ) and ( type(deger)==int or type(deger)==float ):
                sira  = ['celcius','fahrenheit' ,'kelvin' ,'rankin' ]
                sonuc = { 'cel' : [ deger*9 / 5 + 32   , deger+273          , (deger+273)*9/5 ] ,
                          'fah' : [ (deger-32)*5/9     , (deger-32)*5/9+273 , deger+459.69    ] ,
                          'kel' : [ deger-273          , (deger-273)*9/5+32 , deger*9/5       ] ,
                          'rea' : [ (deger-491.69)*5/9 , deger-459.69       , deger*5/9       ] }
                del sira[ sira.index(anlam[arg]) ]
                print deger , anlam[arg] , ':'
                for i in range(3):
                print '  ' , '%.2f'%(sonuc[arg][i]) , ' »' , sira[i]
        else:
                print 'lütfen girdiğiniz değerlere dikkat edin'



