#!/usr/bin/python
# -*- coding: utf-8 -*-

################################################################
# bir sistem kurulumu sonrasında gerekli temel paketler kurulumu
# istediğinizi seçip istediğinizi kaldırabilirsiniz
#
# emineker                                              gruop 19
################################################################


import os

def yukle():
        os.system('sudo apt-get install vlc vim mc zip rar byzanz')     # bazı gerekli paketler
        os.system('sudo apt-get install ubuntu-restricted-extra')       # ubuntu gerekli extra pektlerinin tümü 
        os.system('sudo apt-get install flashplugin-nonfree flashplugin-nonfree-extrasound')    # flash player
        os.system('sudo apt-get install w32codecs libdvdcss2')          # media codec-leri
        os.system('sudo apt-get install sun-java6-jdk')                 # java
        os.system('sudo apt-get install ssh')                           # uzaktan erişim paketi
        os.system('sudo apt-get install splint')                        # programlama için sözdizimi denetimi
        os.system('sudo apt-get install curl github-cli git-core')      # github için
        os.system('sudo apt-get install python-mysqldb python-imaging python-pypdf python-reportlab')   # python paketleri
        os.system('aptitude install mysql-server mysql-client mysql-query-browser')                     # mysql ve extra paketleri kurulumu

        os.system('sudo apt-get -f install')                            # yarım kalan paketleri tamamlar
        os.system('sudo apt-get update')                                # tüm paketleri günceller
        os.system('sudo apt-get upgrade')                               # sistem güncellemesini gerçekleştirir


def vim():
        # programlama için gerekli vim ayarları; python, c ve ruby derlemek için kısayollar
        kaynak = ['syntax enable',
                  'filetype indent on',
                  'set et',
                  'set sw=8',
                  'set smarttab', '\n',
                  'map <f2> :w\|!python %<cr>',
                  'map <f3> :w\|!ruby %<cr>',
                  'map <f4> :w\|!php %<cr>', '\n',
                  'nmap <f9> :SCCompile<cr>'
                  'nmap <c-f9> :SCCompileRun<cr>', '\n',
                  'let g:checksyntax_auto_ruby = 1',
                  'let g:checksyntax_auto_php  = 1',
                  'let g:checksyntax_auto_javascript  = 1',
                  'let g:checksyntax_auto_c = 1']

        with open('/home/' + os.getlogin() + '/.vimrc' , 'w') as dosya:
                [dosya.write(i+'\n') for i in kaynak]


def dns():
        # dns değiştir
        kaynak = '# Generated by NetworkManager\nnameserver 156.154.70.22\nnameserver 156.154.71.22'

        with open('/etc/resolv.conf' , 'w') as dosya:
                dosya.write(kaynak)


if __name__ == "__main__":
        yukle()
        vim()
        dns()
        raw_input('sistem yeniden başlatılacak... >Enter<')
        os.system('sudo reboot')


